#!/bin/bash

# Stash any unstaged changes, so we can run black on all files
git stash -q --keep-index

# Run black on all Python files in the repository
black .

# Restore the stashed changes
git stash pop -q
